export const POST_JOB_LOADER = "POST_JOB_LOADER";
export const POST_JOB = "POST_JOB";
export const SAVE_POST_JOB = "SAVE_POST_JOB";
export const SAVE_POST_JOB_ERROR = "SAVE_POST_JOB_ERROR";

export const POSTED_JOB_LOADER = "POSTED_JOB_LOADER";
export const GET_POSTED_JOB = "GET_POSTED_JOB";
export const SAVE_POSTED_JOB = "SAVE_POSTED_JOB";
